/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import javax.swing.ImageIcon;

/**
 *
 * @author James Chi Yang Ong
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        lblUserName.setText(LoginForm.txtUsername.getText());
        lblUserID.setText("User ID: " + LoginForm.userID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        lblUserName = new javax.swing.JLabel();
        lblUserID = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JLabel();
        AddSubjectbtn = new javax.swing.JLabel();
        Viewtimetablebtn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar3.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar3.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblUserName.setFont(new java.awt.Font("Segoe Marker", 1, 24)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setText("User Name:");
        getContentPane().add(lblUserName);
        lblUserName.setBounds(360, 130, 180, 29);

        lblUserID.setFont(new java.awt.Font("Segoe Marker", 1, 18)); // NOI18N
        lblUserID.setForeground(new java.awt.Color(255, 255, 255));
        lblUserID.setText("User ID:");
        getContentPane().add(lblUserID);
        lblUserID.setBounds(620, 10, 170, 22);

        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/defaultLogOut.png"))); // NOI18N
        logoutbtn.setText("jLabel1");
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutbtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutbtnMouseReleased(evt);
            }
        });
        getContentPane().add(logoutbtn);
        logoutbtn.setBounds(670, 580, 100, 50);

        AddSubjectbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/defaultAddSubject.png"))); // NOI18N
        AddSubjectbtn.setText("jLabel3");
        AddSubjectbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddSubjectbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddSubjectbtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddSubjectbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AddSubjectbtnMouseReleased(evt);
            }
        });
        getContentPane().add(AddSubjectbtn);
        AddSubjectbtn.setBounds(60, 230, 280, 270);

        Viewtimetablebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/defaultViewTimetable.png"))); // NOI18N
        Viewtimetablebtn.setText("jLabel4");
        Viewtimetablebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewtimetablebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewtimetablebtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ViewtimetablebtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ViewtimetablebtnMouseReleased(evt);
            }
        });
        getContentPane().add(Viewtimetablebtn);
        Viewtimetablebtn.setBounds(470, 230, 280, 270);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mainpage.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 823, 667);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    private void logoutbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseEntered
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/image/hoverlogout.png"));
        logoutbtn.setIcon(II);
    }//GEN-LAST:event_logoutbtnMouseEntered

    private void logoutbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseExited
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/image/defaultLogOut.png"));
        logoutbtn.setIcon(II);
    }//GEN-LAST:event_logoutbtnMouseExited

    private void logoutbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/image/pressLogout.png"));
        logoutbtn.setIcon(II);
    }//GEN-LAST:event_logoutbtnMousePressed

    private void logoutbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseReleased
        // TODO add your handling code here:
         LoginForm lf = new LoginForm();
        lf.setVisible(true);
        lf.pack();
        this.dispose();
    }//GEN-LAST:event_logoutbtnMouseReleased

    private void AddSubjectbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddSubjectbtnMouseEntered
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/image/hoverAddSubject.png"));
        AddSubjectbtn.setIcon(II);
    }//GEN-LAST:event_AddSubjectbtnMouseEntered

    private void AddSubjectbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddSubjectbtnMouseExited
        // TODO add your handling code here:
         ImageIcon II = new ImageIcon(getClass().getResource("/image/defaultAddSubject.png"));
        AddSubjectbtn.setIcon(II);
    }//GEN-LAST:event_AddSubjectbtnMouseExited

    private void AddSubjectbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddSubjectbtnMousePressed
        // TODO add your handling code here:
         ImageIcon II = new ImageIcon(getClass().getResource("/image/pressAddSubject.png"));
        AddSubjectbtn.setIcon(II);
    }//GEN-LAST:event_AddSubjectbtnMousePressed

    private void AddSubjectbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddSubjectbtnMouseReleased
        // TODO add your handling code here:
        filterSubjects fs = new filterSubjects();
        fs.setVisible(true);
        fs.pack();
    }//GEN-LAST:event_AddSubjectbtnMouseReleased

    private void ViewtimetablebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewtimetablebtnMouseEntered
        // TODO add your handling code here:
         ImageIcon II = new ImageIcon(getClass().getResource("/image/hoverViewTimetable.png"));
        Viewtimetablebtn.setIcon(II);
    }//GEN-LAST:event_ViewtimetablebtnMouseEntered

    private void ViewtimetablebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewtimetablebtnMouseExited
        // TODO add your handling code here:
          ImageIcon II = new ImageIcon(getClass().getResource("/image/defaultViewTimetable.png"));
        Viewtimetablebtn.setIcon(II);
    }//GEN-LAST:event_ViewtimetablebtnMouseExited

    private void ViewtimetablebtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewtimetablebtnMousePressed
        // TODO add your handling code here:
         ImageIcon II = new ImageIcon(getClass().getResource("/image/pressViewTimetable.png"));
        Viewtimetablebtn.setIcon(II);
    }//GEN-LAST:event_ViewtimetablebtnMousePressed

    private void ViewtimetablebtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewtimetablebtnMouseReleased
        // TODO add your handling code here:
        priority pty = new priority();
        pty.setVisible(true);
        pty.pack();
    }//GEN-LAST:event_ViewtimetablebtnMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddSubjectbtn;
    private javax.swing.JLabel Viewtimetablebtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    public static javax.swing.JLabel lblUserID;
    public static javax.swing.JLabel lblUserName;
    private javax.swing.JLabel logoutbtn;
    // End of variables declaration//GEN-END:variables
}
