/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author James Chi Yang Ong
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        SignUpbtn = new javax.swing.JLabel();
        exitbtn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsername);
        txtUsername.setBounds(230, 200, 350, 30);

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword);
        txtPassword.setBounds(230, 290, 350, 30);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(230, 390, 350, 30);

        SignUpbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/defaultSignUp.png"))); // NOI18N
        SignUpbtn.setText("jLabel2");
        SignUpbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SignUpbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SignUpbtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SignUpbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SignUpbtnMouseReleased(evt);
            }
        });
        getContentPane().add(SignUpbtn);
        SignUpbtn.setBounds(230, 460, 350, 63);

        exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/defaultExit.png"))); // NOI18N
        exitbtn.setText("jLabel3");
        exitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitbtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitbtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitbtnMouseReleased(evt);
            }
        });
        getContentPane().add(exitbtn);
        exitbtn.setBounds(680, 600, 100, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/SignUpPage.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 800, 667);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void SignUpbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpbtnMouseEntered
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/image/hoverSignUp.png"));
        SignUpbtn.setIcon(II);
    }//GEN-LAST:event_SignUpbtnMouseEntered

    private void SignUpbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpbtnMouseExited
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/image/defaultSignUp.png"));
        SignUpbtn.setIcon(II);
    }//GEN-LAST:event_SignUpbtnMouseExited

    private void SignUpbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpbtnMousePressed
        // TODO add your handling code here:
        ImageIcon II = new ImageIcon(getClass().getResource("/image/pressSignUp.png"));
        SignUpbtn.setIcon(II);
    }//GEN-LAST:event_SignUpbtnMousePressed

    private void SignUpbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpbtnMouseReleased
        // TODO add your handling code here:
         String username = txtUsername.getText();
        String pw = txtPassword.getText();
        String email = txtEmail.getText();
        
        //conect to database.
        Connection conn = DBConnection.getConnection();
        
        //if successfull connect.
        PreparedStatement ps;
        if(("".equals(username) && "".equals(pw) && "".equals(email)) || ("".equals(pw) && "".equals(email)) || ("".equals(username) && "".equals(pw) ) || ("".equals(username) && "".equals(email)) || ("".equals(username)) || ( "".equals(pw)) || ( "".equals(email)) ){
              JOptionPane.showMessageDialog(null, "Error Please fill up the registration form");
        }else{
        
             try {
            //insert into databse/query.  ?????? will be insert into first 1st, 2nd, 3nd and so on. Each of the ?  <--
            ps = conn.prepareStatement("INSERT INTO login_account(username,password,email) VALUES (?,?,?)");
            ps.setString(1, username);
            ps.setString(2, pw);
            ps.setString(3, email);
           
            
            if(ps.executeUpdate() > 0){
                JOptionPane.showMessageDialog(null, "New Member Added Sign Up Successfully"); // if can enter successsfully.
                 LoginForm lf = new LoginForm();
                lf.setVisible(true);
                lf.pack();
               this.dispose();
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
       
      
        
//        MainForm.lblMembers.setText("Society Members: " + Integer.toString(DashboardFunction.countData("membership")));
        
  // after successfully insert it will set back to downbelow.
        txtUsername.setText("");
        txtPassword.setText("");
        txtEmail.setText("");
    }//GEN-LAST:event_SignUpbtnMouseReleased

    private void exitbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseEntered
        // TODO add your handling code here:
         ImageIcon II = new ImageIcon(getClass().getResource("/image/hoverExit.png"));
        exitbtn.setIcon(II);
    }//GEN-LAST:event_exitbtnMouseEntered

    private void exitbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseExited
        // TODO add your handling code here:
         ImageIcon II = new ImageIcon(getClass().getResource("/image/defaultExit.png"));
        exitbtn.setIcon(II);
    }//GEN-LAST:event_exitbtnMouseExited

    private void exitbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMousePressed
        // TODO add your handling code here:
         ImageIcon II = new ImageIcon(getClass().getResource("/image/pressExit.png"));
        exitbtn.setIcon(II);
    }//GEN-LAST:event_exitbtnMousePressed

    private void exitbtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitbtnMouseReleased
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitbtnMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SignUpbtn;
    private javax.swing.JLabel exitbtn;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
