/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author James Chi Yang Ong
 */
public class ViewTimeTable extends javax.swing.JFrame {

    public static String timetableid;
    public static int time = 800;
    public static String[] obj = {"MONDAY", "TUEDAY", "WEDNESDAY", "THURSDAY", "FRIDAY"};

    /**
     * Creates new form ViewTimeTable
     */
    public ViewTimeTable() {
        initComponents();
        lblUserName.setText("User Name: " + LoginForm.txtUsername.getText());
        lblUserID.setText("User ID: " + LoginForm.userID);
        fillSubjectTable(userTimetable);
//        fillTimetable(timetable);
    }

    public static void fillSubjectTable(JTable table) {
        Connection conn = DBConnection.getConnection();
        PreparedStatement ps;

        try {
            ps = conn.prepareStatement("SELECT * FROM user_timetable WHERE user_id = ?");
            ps.setString(1, LoginForm.userID);

            ResultSet rs = ps.executeQuery(); //set all query result in resultset.

            DefaultTableModel model = (DefaultTableModel) table.getModel();

            Object[] row;
            while (rs.next()) {
                row = new Object[7];
                row[0] = rs.getString(4); //subject code
                row[1] = rs.getString(5); //subject name
                row[2] = rs.getString(9); //date
                row[3] = rs.getInt(6); //start time
                row[4] = rs.getInt(7); //end time
                row[5] = rs.getString(8); //venue
                row[6] = rs.getString(10); //lecturer
                timetableid = rs.getString(1);
                model.addRow(row);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddSubjectForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

//     public static void fillTimetable(JTable table) {
//        Connection conn = DBConnection.getConnection();
//        PreparedStatement ps;
//
//        try {
//            ps = conn.prepareStatement("SELECT * FROM user_timetable WHERE user_id = ?");
//            ps.setString(1, LoginForm.userID); 
//            
//            ResultSet rs = ps.executeQuery(); //set all query result in resultset.
//
//            DefaultTableModel model = (DefaultTableModel) table.getModel();
//
//            Object[] row;
//            Object[][] col;
//            while (rs.next()) {
//                col = new Object[5][8];
//                row = new Object[7];
//                row[0] = rs.getString(4); //subject code
//                row[1] = rs.getString(5); //subject name
//                row[2] = rs.getString(9); // subject date
//                row[3] = rs.getInt(6); // subject start date
//                row[4] = rs.getInt(7); //subject end date
//                row[5] = rs.getString(8);
//                row[6] = rs.getString(10);
//                
//                for(int i = 1; i <= 10;i++){
//                    if(rs.getInt(6)== time){ //if true move to the j loop
//                     for(int j = 1; i<=5;j++){ //check days
//                        if(obj[j].equals(rs.getString(9))){
//                            col[i][j] = rs.getString(4);
//                        }
//                       }
//                    }
//                    time += 100;
//                }
//   
//                model.addRow(row);
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(AddSubjectForm.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTimetable = new javax.swing.JTable();
        lblUserName = new javax.swing.JLabel();
        lblUserID = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        timetable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("My Timetable");

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        userTimetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject Code", "Name", "Date", "Start Time", "End Time", "Venue", "Lecturer"
            }
        ));
        userTimetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTimetableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userTimetable);

        lblUserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUserName.setText("User Name:");

        lblUserID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUserID.setText("User ID");

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        timetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Monday", null, null, null, null, null, null, null, null, null, null, null},
                {"Tuesday", null, "", null, null, null, null, null, null, null, null, null},
                {"Wednesday", null, null, null, null, null, null, null, null, null, null, null},
                {"Thusday", null, null, null, null, null, null, null, null, null, null, null},
                {"Friday", null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Date/Time", "0800", "0900", "1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700", "1800"
            }
        ));
        jScrollPane2.setViewportView(timetable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(89, 89, 89)
                        .addComponent(lblUserName)
                        .addGap(160, 160, 160)
                        .addComponent(lblUserID))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUserName)
                    .addComponent(lblUserID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void userTimetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTimetableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userTimetableMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) userTimetable.getModel();
        int rowIndex = userTimetable.getSelectedRow();

        if (timetableid.equals("")) {
            JOptionPane.showMessageDialog(null, "No Record Selected!");
        } else {
            int ttid = Integer.valueOf(timetableid);

            Connection conn = DBConnection.getConnection();
            PreparedStatement ps; //set the variable.

            try {
                ps = conn.prepareStatement("DELETE FROM user_timetable WHERE timetable_id = ?");
                ps.setInt(1, ttid);

                if (ps.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "Subject Record Deleted");
                }
            } catch (SQLException ex) {
                Logger.getLogger(ViewTimeTable.class.getName()).log(Level.SEVERE, null, ex);
            }
            userTimetable.setModel(new DefaultTableModel(null, new Object[]{"Subject Code", "Name", "Date",
                "Start Time", "End Time", "Venue", "Lecturer"}));
            fillSubjectTable(userTimetable);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTimeTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTable timetable;
    private javax.swing.JTable userTimetable;
    // End of variables declaration//GEN-END:variables
}
